### ISSUE TITLE
Windows Version.

### ISSUE THREAD

**Issue by ghost** [univrsal/spectralizer#1]
I was wondering if this got Windows support. I could really use this.

**Comment by univrsal** [comment]
As soon as it's finished, yes. I just wasn't satisfied with how it looked so I haven't released it

**Comment by ghost** [comment]
@univrsal Ahh wonderfull. Good luck

**Comment by univrsal** [comment]
Alrighty, So I just compiled it on windows and it seems to be running fine. Once I've finished the remaining todo items I'll make a release.
![image](https://user-images.githubusercontent.com/8353672/67024916-b4f2ac80-f0f4-11e9-9dd5-8f863dfe275f.png)

**Comment by viktordimov** [comment]
I could use a linux release.
Found this on `/package/package-linux.sh`
```
build_location="../../../qtc-release/rundir/Release/obs-plugins/64bit"
```
The resulting `bin/64bit` is empty.

**Comment by univrsal** [comment]
the linux package script isn't updated yet, but the script only copies the builds into a zip archive so you can technically just build it yourself and get the binaries manually

**Comment by univrsal** [comment]
@dorianxonic I have a linux release ready if you still want to give this a try
[spectralizer.v1.1.linux64.zip](https://github.com/univrsal/spectralizer/files/3756947/spectralizer.v1.1.linux64.zip)

**Comment by viktordimov** [comment]
@univrsal I just tried it, uncompressed the 'plugin' folder inside `~/.config/obs-studio/plugins/spectralizer`. The plugin doesn't show up in OBS, perhaps I'm missing some dependencies?

**Comment by univrsal** [comment]
yeah you need libfftw3, but it should be installed on most distros
