### ISSUE TITLE
linux.ubuntu.64 release doesn't work but debug.linux.ubuntu.64 does?

### ISSUE THREAD

**Issue by treierxyz** [univrsal/spectralizer#12]
Seemed like the linux.ubuntu.64 release didn't work and tried the debug release to find the cause, but it just works with the debug one. Just a weird phenomenon, maybe a compiling error?

**Comment by treierxyz** [comment]
Otherwise the debug release works fine.

**Comment by univrsal** [comment]
yeah the debug one contains a fix that the other one's didn't, I haven't updated them because the person I made the debug built for never responded. I've deleted the other one's for now

**Comment by treierxyz** [comment]
Understandable. Have a good day!
