### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by arcandio** [univrsal/spectralizer#13]
I've tried a number of different configurations of copying files from the zip file into the `obs-studio` folder, and none have succeeded. I'm trying to follow the directions here: https://obsproject.com/forum/resources/spectralizer.861/ but there *is* no "plugin" folder in the spectralizer zip folder.

1. I tried copying the root folder in the archive, `spectralizer-master` into `obs-studio` but that didn't work.
2. I tried copying the contents of `spectralizer-master` into `obs-studio` but that didn't work.
3.  I tried copying `spectralizer-master` into `obs-studio/obs-plugins` both in Program Files (x86)` and `AppData/Roaming` and neither of those worked.

Any help would be appreciated.

I'm on windows 10, OBS 24.0.3 64-bit.

**Comment by univrsal** [comment]
You downloaded the source code not the actual plugin. Please download the [binary from the release page](https://github.com/univrsal/spectralizer/releases/latest)

**Comment by arcandio** [comment]
Thanks. That of course was the problem.
