### ISSUE TITLE
Visualiser files cannot be found, so the visualiser is not available

### ISSUE THREAD

**Issue by R0ck3tLad** [univrsal/spectralizer#14]
I've followed installation of the plugin to a T, and all the files are in their right places, but when i run obs and look at the log it says it cannot find any of the .dll files it needs, despite them all being where they need to be. I'm running the latest possible version of obs, and i've even tried restarting my device to see if that would help.

**Comment by univrsal** [comment]
I need the log file

**Comment by R0ck3tLad** [comment]
[2020-02-15 10-43-08.txt](https://github.com/univrsal/spectralizer/files/4207413/2020-02-15.10-43-08.txt)
yeet

**Comment by univrsal** [comment]
You are using a two year old obs version, you need at least 24.0.0 for spectralizer to work

**Comment by R0ck3tLad** [comment]
Ah. Seems the check for updates function didn't want to play. Sorry for the hassle!
