### ISSUE TITLE
[Feature Rquest] Waveform Mode

### ISSUE THREAD

**Issue by ghost** [univrsal/spectralizer#18]
This is an awesome plugin and one thing I would love to see is a Waveform styled Spectrum

**Comment by univrsal** [comment]
You mean something like this?
![img](https://cdn.discordapp.com/attachments/374637102551400468/696746219535466606/unknown.png)
If so I'm working on it.

**Comment by ghost** [comment]
I was think more of this 
![Screenshot_20200408_151906](https://user-images.githubusercontent.com/37266538/78788693-6f7cb100-79ac-11ea-96f0-d8fe7358a987.jpg)

**Comment by ghost** [comment]
Also that Waveform type in your screenshot is also something I want. Maybe have a Box to fill it completely?

**Comment by univrsal** [comment]
Filling in is already possible by changing the mode

**Comment by ghost** [comment]
Thats awesome

**Comment by jrwagz** [comment]
@univrsal , is the `mode` option available in version 1.2?  I'm looking for a way to bend the standard bars around a circle, so that the bars shoot out like radials from the center of the circle.  Would that be a hard mode to add?

**Comment by MCOfficer** [comment]
@jrwagz it was commited after 1.2, so it oughta be in the next release.

**Comment by univrsal** [comment]
Yeah I haven't made a new release, yet. It'll probably also take a bit until the next one. I have to figure out some things first, mainly CI and installers for all platforms. I also want to fix the scale issue from #3 and maybe even add some style options like rounded corners and a radial option.

**Comment by MCOfficer** [comment]
If it comes to CI (specifically github actions), i might be able to help.

**Comment by univrsal** [comment]
I already have CI going for one of my other plugins, the biggest issue will probably creating the *.pkg for macOS.

**Comment by MCOfficer** [comment]
I recently stumbled over [fpm](https://github.com/jordansissel/fpm), which can also create .pkg packages. maybe that helps.

**Comment by Silver-Streak** [comment]
I second the desire for a circular visualizer. I currently use the Win10 App Kauna, which lets me do this: 

![image](https://user-images.githubusercontent.com/24237149/92863187-44feac00-f3c1-11ea-9ed4-9610d13ab955.png)


But as it's a Win10 App, it's a huge pain in the butt to capture consistently in OBS. I'd love to be able to reproduce this type of waveform in this add-on.
