### ISSUE TITLE
Install Failure

### ISSUE THREAD

**Issue by RONCOmke** [univrsal/spectralizer#19]
I've run the install-mac.sh code with brew and run into an error. fftw is already installed so I tried copying over the bin and data folders into the user library application support, but the spectralizer still isn't coming up as an option in OBS. Can you please suggest next steps or what additional information you need to assist.

**Comment by univrsal** [comment]
I need the obs studio log
![log](https://user-images.githubusercontent.com/8353672/79021780-f330cc00-7b6b-11ea-888b-171b1b998301.png)

**Comment by RONCOmke** [comment]
Hi Alex,

https://obsproject.com/logs/IuJyP8S4fGgtgJ2b

Thanks!
RONCO

**Comment by univrsal** [comment]
The log shows that the plugin is loaded, so there shouldn't be any issues. It should show up as a source option in obs studio

**Comment by nokturnal** [comment]
More as an informational add-on for @univrsal ... From memory, for me the install-mac.sh did not properly copy the required files to the OBS plugin folder but did install all required dependencies. Manually moving the files outlined in the Mac installation directions to the OBS plugin directories did fix the issue for me.  Good luck!

**Comment by univrsal** [comment]
Yeah I think I screwed something up in the script, but I just haven't gotten myself to update it. I only have macOS on my laptop which I rarely use right now so I don't know when I'll get around to fixing it.

**Comment by martindefatte** [comment]
I see a data folder but not a "bin" folder inside the ".zip", as the instructions state. Also, the Application Support folder is in the OS' Library, not the individual user Library, so that's probably why the install script doesn't work.

**Comment by univrsal** [comment]
Nah the files are definitely in the zip file you probably just downloaded the source code and not the actual release. The script also install script moves it to the user library, I just screwed the move command up I think

**Comment by martindefatte** [comment]
hmmm. yeah, i grabbed the source code. I don't see a link to the a release package on github. Just the clone/download zip.

**Comment by martindefatte** [comment]
DERP. My bad. Found it. I think I needed that nudge to look for it. (Not super familiar with GitHub repo structure.)

**Comment by ACB-prgm** [comment]
Just FYI.  I was having issues, but then updated homebrew and reinstalled and it worked. Also did brew install fftw.
