### ISSUE TITLE
Not appearing as a source in OBS

### ISSUE THREAD

**Issue by orhochris** [univrsal/spectralizer#22]
I've tried installing this in a number of places and no matter what I do, it never appears as a source. I've tried extracting to the OBS-studio folder, the plugins folder, the 64 bit folder, and more folders up and down the chain. No matter what I try, I have no evidence that this is functioning.

**Comment by univrsal** [comment]
What operating system are you on? I need the obs log after you tried installing it.
![log](https://user-images.githubusercontent.com/8353672/82864848-0083f900-9f15-11ea-9cd3-abfe58c9b418.png)
if you are on windows please follow [this guide](https://www.youtube.com/watch?v=C8mDmBKKbUw) closely.

**Comment by LunarLambda** [comment]
I couldn't get it to work either (Linux 64-bit)

https://obsproject.com/logs/iaBL__zjsdhOv5Jh

**Comment by univrsal** [comment]
> 
> 
> I couldn't get it to work either (Linux 64-bit)
> 
> https://obsproject.com/logs/iaBL__zjsdhOv5Jh

It's not loading the plugin. Did you read and follow the installation section on the obs forums?

**Comment by BLCRAFT210** [comment]
I got this to work following the instructions on Linux 64 bit.

**Comment by LunarLambda** [comment]
I followed the instructions from the forums

```
.config/obs-studio/plugins/spectralizer:
drwxr-xr-x - luna  7 Feb 13:37 bin/
drwxr-xr-x - luna  7 Feb 13:37 data/

.config/obs-studio/plugins/spectralizer/bin:
drwxr-xr-x - luna  7 Feb 13:37 64bit/

.config/obs-studio/plugins/spectralizer/bin/64bit:
.rwxr-xr-x 548k luna  7 Feb 13:37 spectralizer.so*

.config/obs-studio/plugins/spectralizer/data:
drwxr-xr-x - luna  7 Feb 13:37 locale/

.config/obs-studio/plugins/spectralizer/data/locale:
.rw-r--r-- 1,2k luna  7 Feb 13:37 en-US.ini
.rw-r--r-- 1,1k luna  7 Feb 13:37 ko-KR.ini
```

It does not work.
I'm using `fftw 3.3.8-3`.
Obs version `25.0.8-1`.

**Comment by LunarLambda** [comment]
It appears the plugin is missing some symbols OBS is expecting

`LD_DEBUG=libs obs |& grep -i spectralizer`:

```
      5096:	calling init: /home/luna/.config/obs-studio/plugins/spectralizer/bin/64bit/spectralizer.so
      5096:	/home/luna/.config/obs-studio/plugins/spectralizer/bin/64bit/spectralizer.so: error: symbol lookup error: undefined symbol: obs_module_post_load (fatal)
      5096:	/home/luna/.config/obs-studio/plugins/spectralizer/bin/64bit/spectralizer.so: error: symbol lookup error: undefined symbol: obs_module_name (fatal)
      5096:	/home/luna/.config/obs-studio/plugins/spectralizer/bin/64bit/spectralizer.so: error: symbol lookup error: undefined symbol: obs_module_author (fatal)
```

Completely inexplicably, the source does show up now. Though the plugin seems to be incompatible with glava.

**Comment by univrsal** [comment]
Those functions are optional, so they don't prevent it from loading. What do you mean by incompatible with glava?

**Comment by LunarLambda** [comment]
glava is a desktop audio visualizer program. when it is running,
spectralizer fails to capture desktop audio.

**Comment by univrsal** [comment]
What audio input are you using? An obs audio source or an mpd fifo? Because fifos can only be accessed by one process, you'll have to add a new fifo for each process.

**Comment by LunarLambda** [comment]
Desktop Audio, though I can switch to OBS media source. It's just something
I noticed while setting things up

**Comment by spartagp** [comment]
I've tried installing this in a number of places and no matter what I do, it never appears as a source. I've tried extracting to the OBS-studio folder, the plugins folder, the 64 bit folder, and more folders up and down the chain. No matter what I try, I have no evidence that this is functioning.

**Comment by spartagp** [comment]
https://obsproject.com/logs/wOgUkQMQHkAn3suN

**Comment by univrsal** [comment]
> https://obsproject.com/logs/wOgUkQMQHkAn3suN

Just use the installer once I make the new release
