### ISSUE TITLE
Missing Audio Sources

### ISSUE THREAD

**Issue by ftrocchi** [univrsal/spectralizer#29]
I have a GoXLR.  It has audio devices on windows for chat, music, system, and mic.  I would like to just pull the music channel, but it isn't listed.  Perhaps adding the ability to query the OS and use those devices... independent of what devices are selected in OBS.

**Comment by univrsal** [comment]
That's out of scope, OBS offers an easy way to get audio from obs audio sources, but not for anything else. I'd have to completely copy over the audio capture implementation, which I'm not going to do.

**Comment by ftrocchi** [comment]
I appreciate your response, and can understand how monumental it would be.  But as it sits now the plugin is of no use to me, and I suspect many others.  I have other ways I can do it.... just thought this plugin would do the trick easier.  Close but not quite.  Thanks again. and good luck.
