### ISSUE TITLE
 I can't install correctly

### ISSUE THREAD

**Issue by spartagp** [univrsal/spectralizer#30]
I've tried installing this in a number of places and no matter what I do, it never appears as a source. I've tried extracting to the OBS-studio folder, the plugins folder, the 64 bit folder, and more folders up and down the chain. No matter what I try, I have no evidence that this is functioning.

**Comment by univrsal** [comment]
have you tried watching the installation video? It's pretty clear where the files have to go, the log you posted shows that obs is not trying to load the plugin so the files aren't in the right place.

**Comment by djGrabko** [comment]
Could you provide a link to the installation video?  Thanks :)

**Comment by univrsal** [comment]
https://obsproject.com/forum/resources/spectralizer.861/ scroll down to installation
