### ISSUE TITLE
Source not appearing while module is loaded

### ISSUE THREAD

**Issue by AMDITAR** [univrsal/spectralizer#32]
I've followed the installation instructions and copied files to the correct locations, but spectralizer does not show up as a source in OBS, despite the fact that in the OBS log it says it's loaded.  Thanks in advance for your support. 

https://obsproject.com/logs/2nRfZjeZHwY4z5aI

![Screenshot 2020-09-15 122948](https://user-images.githubusercontent.com/62975330/93238264-37457f80-f74f-11ea-87e8-b9253bab20be.png)

**Comment by univrsal** [comment]
Yeah that's just me being a genius and giving the source a different name. It's called audio visualizer :P third from the top, I'll probably have to rename it since this has happened a few times
