### ISSUE TITLE
[Bug] It seems there is a bug in visualizer_source::update

### ISSUE THREAD

**Issue by walker-WSH** [univrsal/spectralizer#33]
Hello:
While studying this plugin, I find this code:
If "!m_visualizer" then delete m_visualizer ?

Should we check _if(m_visualizer!=NULL)_ before deleting it ?
Please confirm it, thanks.

![1600914039](https://user-images.githubusercontent.com/18413354/94093402-b32a8080-fe4f-11ea-9398-f3b0cb4cb9d8.png)

**Comment by univrsal** [comment]
No because deleting a null pointer doesn't do anything.
