### ISSUE TITLE
"Audio Visualizer" not appearing in OBS studio

### ISSUE THREAD

**Issue by ghost** [univrsal/spectralizer#4]
When I right click to add a new audio visualizer, it is not appearing despite following installation instructions. I'm not sure if this is the correct way you add a visualizer source. Hoping I can get some help on this one.

**Comment by univrsal** [comment]
Can you give me a log of obs studio? Also where did you extract the plugin and what did you extract?

**Comment by ghost** [comment]
I extracted the zip folder to my desktop, and then moved "data" and "obs-plugins" to my directory where the same file names are. Do you know how I can get a log of OBS?

**Comment by univrsal** [comment]
![image](https://user-images.githubusercontent.com/8353672/67163596-1cb52b80-f371-11e9-9c6b-82f46a034999.png)

**Comment by teliot36** [comment]
Is it safe to upload this? Please let me know as soon as possible
https://obsproject.com/logs/jE17PkS_6D19JY-7

**Comment by univrsal** [comment]
yes it wouldn't be an option otherwise

**Comment by univrsal** [comment]
You're not using the latest version of obs, which is what I used to compile the plugin. You'll most likely have to update

**Comment by ghost** [comment]
Omg thank you so much! Such a silly mistake on my part. I truly had no idea.
Can't wait to use all of your plugins! :) WOW!!!

**Comment by univrsal** [comment]
no problem, don't get too excited for the visualizer though, I've heard it doesn't properly work for everyone currently, which I'm trying to fix

**Comment by NaderStreamer** [comment]
It doesn't work for me. I have pkg version installed. It doesn't appear in my OBS
