### ISSUE TITLE
Install not fully working for release 1.3.0 - possible missing DLL?

### ISSUE THREAD

**Issue by tdwhite0** [univrsal/spectralizer#41]
I installed the latest 1.3.0 from spectralizer.v1.3.0.bin.windows and the source didn't show up in OBS. I then downloaded 1.2 and noticed it included a dll that 1.3.0 didn't have: libfftw3-3.dll. Installing 1.2 first and then installing 1.3.0 afterwards, it worked as I expected. Great work by the way, love the radial addition.

**Comment by univrsal** [comment]
just use the installer for now

**Comment by univrsal** [comment]
fixed it now
