### ISSUE TITLE
1.3.1 installs plugin into a wrong directory

### ISSUE THREAD

**Issue by yurivict** [univrsal/spectralizer#43]
1.2 installed it into lib/obs-plugins/spectralizer.so where it is looked at.
1.3.1 installs it into spectralizer/bin/64bit/spectralizer.so where obs-studio doesn't look for plugins.

**Comment by univrsal** [comment]
You need to set ``-DGLOBAL_INSTALLATION=ON`` when configuring otherwise it'll build a portable and install it to ``CMAKE_INSTALL_PREFIX``

**Comment by yurivict** [comment]
GLOBAL_INSTALLATION helps, thanks.
