### ISSUE TITLE
Spectrum is broken when starting OBS

### ISSUE THREAD

**Issue by NxRoot** [univrsal/spectralizer#47]
Every time I open OBS I need to open the spectralizer component and fix the 'Detail' field.
i dont want to be doing this every time i enter obs. Footage on below link.

[VIDEO](https://streamable.com/ie9ju2)

Image:
![Image Of Bug fixing](https://i.ibb.co/y0V2Wfy/Untitled.png)

**Comment by univrsal** [comment]
I need the obs studio log and a screenshot of the entire properties for the source

**Comment by univrsal** [comment]
Most likely a duplicate of #38
