### ISSUE TITLE
Allow transparent color selection

### ISSUE THREAD

**Issue by fefo-dev** [univrsal/spectralizer#48]
One of the newer updates made so filters now work on the source, but simply adding a color correction filter adds a lot of blur to the edges:

https://imgur.com/a/IOsra3S

Can you add support to alpha channels to add transparency without losing clarity?

Thanks, love this tool.

**Comment by univrsal** [comment]
Set the filtering to Point.
![image](https://user-images.githubusercontent.com/8353672/106022103-c97a6e80-60c5-11eb-92ca-7103d6a78217.png)
I might add it though regardless.

**Comment by fefo-dev** [comment]
Wow, thanks for the tip.
