### ISSUE TITLE
Can't detect some sounds

### ISSUE THREAD

**Issue by jayare5** [univrsal/spectralizer#51]
I'm having an issue where some sounds seem to be too short for the visualizer to pick up.
The easiest way for me to find this problem is when I play Nintendo Switch and navigate the menu. The cursor sound doesn't get picked up, but everything else does once there's music or longer sounds, like the coming in and out of the home menu sounds.
I've spent a few hours testing lots of different options, even passing the game sound through the "Desktop" sound and making the plugin read it from there instead, I've tried overly equalizing the audio too, nothing works. (Again, unless there's music, that's when this plugin works normally and I have no problem with it)

As you can see here, OBS's normal sound monitor detects it just fine, and it's quite high! I'm confused as to why exactly this plug-in won't read it so for now I'm assuming it has to do with short sounds.
![Detecting sound](https://user-images.githubusercontent.com/26237704/110578523-05780900-8133-11eb-8821-2b76776cea07.png)

**Comment by univrsal** [comment]
Try disabling automatic scaling and lowering the gravity

**Comment by jayare5** [comment]
> Try disabling automatic scaling and lowering the gravity

Nope, still nothing!
![image](https://user-images.githubusercontent.com/26237704/110702189-35212280-81c0-11eb-9c71-b00c85d382b2.png)

And here, just to make sure that it is still working, I put a game with music but the bars are just all the way up :P I mean, that's what I would expect since with that option the scaling is up to the user, but still, just showing that it is sensitive to sound but it still wont pick up the short cursor sound (or any other short sound that's surrounded by silence).

![image](https://user-images.githubusercontent.com/26237704/110702356-6994de80-81c0-11eb-9fb9-a15ea715f8ff.png)

**Comment by univrsal** [comment]
Setting the scale to logarithmic and playing with the other settings helps, but honestly this is not what the visualizer was made for so you'll probably not get the results you want.
