### ISSUE TITLE
Does not work with asio devices set to less than 512 samples. 

### ISSUE THREAD

**Issue by lcalder** [univrsal/spectralizer#52]
If I set my asio device to use fewer than 512 samples the visualizer will do nothing, even though OBS sees the audio signals just fine as evidenced by the audio meter activity. As soon as I adjust the sample size to 512, spectralizer will spring to life...

**Comment by univrsal** [comment]
I'll just merge this with #21 as the sample count seems to be an issue with other audio inputs as well
