### ISSUE TITLE
Colors not correct in select color

### ISSUE THREAD

**Issue by mccla5214** [univrsal/spectralizer#57]
When selecting colors only red is correctly reproduced.
Open spectralizer properties,
Press select color,
select color green
press ok

Wrong color is shown

**To Reproduce**

**Expected behavior**
Expected correct color to be shown

**Screenshots**
![image](https://user-images.githubusercontent.com/15841126/135735123-e968b89e-cf44-488d-b5ff-aecc5825e21c.png)

**Log**
https://obsproject.com/logs/S5sFo9cCPMG6_EZx

**Additional context**

**Comment by univrsal** [comment]
Is there a reason you added a color correction filter to the source?

**Comment by mccla5214** [comment]
No there isn't,  should I remove it

Mike

**Comment by mccla5214** [comment]
I just removed it,  thank you for finding that,  I don't know how I put it
there but I won't do it again

Mike
