### ISSUE TITLE
more a question than an issue

### ISSUE THREAD

**Issue by hasnaio** [univrsal/spectralizer#59]
hello! as the title suggest, i have a question about the plugin, does it work with streamlabs? and if it doesn't, is there any chance that it will in the future? thanks :)

**Comment by univrsal** [comment]
No, streamlabs obs doesn't support plugins. They apparently made some effort to change this recently, but I don't have any intention on porting my plugins currently (if it's even possible), because obs studio is the superior program in my opinion.
