### ISSUE TITLE
It doesn't work at all.

### ISSUE THREAD

**Issue by OriginalSchmuck** [univrsal/spectralizer#6]
I am total noob at this, but moving the .dll or folder anywhere in the obs-studio installed location does absolutely nothing.  It doesn't show up at all in the Tools section of OBS (using 24.0.3).

**Comment by OriginalSchmuck** [comment]
I rewatched EposVox's video coverage on this only to realize it's a source.  I'm a noob.  But there's no documentation anywhere about it being a source.  maybe I am an idiot, but it took way too long to figure that out.

**Comment by univrsal** [comment]
I mean how else would it work? All things related to video in obs-studio are sources

**Comment by OriginalSchmuck** [comment]
Like I said.  I am noob.

**Comment by univrsal** [comment]
yeah no worries
