### ISSUE TITLE
Will a Mac plugin be available in the future as well? Really great project.

### ISSUE THREAD

**Issue by Bram-Brooks** [univrsal/spectralizer#8]
Hi,

This is a really nice plugin, sadly it doesn't seem to be available for Mac. Any idea if you can tell if it will be available for Mac OS as well in the future? Thanks in advance.

**Comment by univrsal** [comment]
As with all my other plugins my answer is "technically yes", as in I use no code that couldn't run on macOS. But since developing for mac is basically impossible without owning an apple device I can't do it myself.

**Comment by Zettt** [comment]
Do you have build instructions anywhere? I'd have a stab at it.

**Comment by univrsal** [comment]
First follow the [official build instructions](https://github.com/obsproject/obs-studio/wiki/install-instructions#macos-build-directions) for obs-studio and then [my instructions](https://github.com/univrsal/input-overlay/wiki/Compiling), just replace input-overlay with spectralizer and ignore everything after ``add_subdirectory(...)``
Then get [FFTW](http://fftw.org/install/mac.html). After that you'll need to open the obs source folder in CMake and set ``FFTW_INCLUDE_DIRS`` to the folder that contains fftw3.h and ``FFTW_LIBRARIES`` to the fftw3 binary. I don't know exactly how it's distributed on macOS, so I can't help you too much with that.
Then if you run ``cmake .. && make`` inside the obs-studio folder again you should get a obs build with spectralizer included.

**Comment by univrsal** [comment]
Well, I've gotten my hands on macOS and made a test build. If anybody would like to test it you can get it [here](https://github.com/univrsal/spectralizer/files/4215501/spectralizer.v1.2.mac.zip). Make sure to install [fftw](http://fftw.org/). Compiled and tested on Catalina 10.15.3

**Comment by Bram-Brooks** [comment]
@univrsal That's amazing news! Huge thanks for this. I'm running some tests the next few days and will let you know if I find any weird bugs.

**Comment by jgpeak** [comment]
@univrsal I pulled your test build from [here](https://github.com/univrsal/spectralizer/files/4215501/spectralizer.v1.2.mac.zip) and was able to manually install it mimicking what your install-mac.sh script is suppose to do. THAT script in the main package doesn't work since there is no plugins folder for it to copy and it doesn't trigger any kind of automated build in order to create that plugin folder for the script to work correctly.

Hope this description helps and happy to help you test this for mac to get the bugs worked out.

**Comment by univrsal** [comment]
I'll try and update the script

**Comment by luizeof** [comment]
@jgpeak working fine on MacOS Catalina (with homebrew)

![Captura de Tela 2020-05-10 às 11 12 56](https://user-images.githubusercontent.com/257004/81501557-73ec0080-92af-11ea-9774-d975ebcee5b9.png)

**Comment by Bram-Brooks** [comment]
Running great here as well on Mac OS Catalina 10.15.4 with OBS 25.0.8. Very nice plugin, thanks.

**Comment by AtAFork** [comment]
@jgpeak thanks for this tip! I was getting the error `mv: rename plugin/* to /Users/myusername/Library/Application Support/obs-studio/plugins/spectralizer/*: No such file or directory` but fixed it by copying the `plugin` folder into the `package` folder and then re-running `install-mac.sh`.

@univrsal I recommend updating instructions on the Release page for this. Also, thanks for creating a fantastic plugin!

**Comment by mustafamohsenm** [comment]
Not working. Plugin doesn't even show in the available sources
macOS 10.15.6 (Catalina)
OBS 26.1.2
Spectralizer 1.3.4

**Comment by Zero1Infinity** [comment]
> Not working. Plugin doesn't even show in the available sources
> macOS 10.15.6 (Catalina)
> OBS 26.1.2
> Spectralizer 1.3.4

Make sure you read the installation instructions which states you run:

brew install fftw
