### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by Cednonymous** [univrsal/spectralizer#9]
I'm pretty new at this, but how do i install this plugin?

**Comment by univrsal** [comment]
Have you read the forum post? It contains instructions on how to install the plugin

**Comment by Parcanss** [comment]
They aren't very clear, I can't get it to worth either.

**Comment by Dracmpire** [comment]
Sorry but can you point me towards the forum post? I cannot find it.

**Comment by univrsal** [comment]
https://obsproject.com/forum/resources/spectralizer.861/
